import React, { createContext, useState, useContext } from 'react';
import { Animated } from 'react-native';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Home Screen
    greeting: "Hi Yogi! 👋",
    actionRequired: "Action Required",
    overdue: "overdue",
    dueToday: "due today",
    todaySnapshot: "Today's Snapshot",
    inProgress: "In Progress",
    ready: "Ready",
    trial: "Trial",
    unpaid: "Unpaid",
    cashIn: "Cash In",
    outstanding: "Outstanding",
    profit: "Profit",
    searchPlaceholder: "Search by name, phone, order...",
    status: "Status",
    payment: "Payment",
    today: "Today",
    upcoming: "Upcoming",
    allOrders: "All Orders",
    orders: "Orders",
    order: "Order",
    focusMode: "🔥 Focus Mode",
    loading: "Loading your orders...",
    allClear: "All clear for today! 🎉",
    noUpcoming: "No upcoming orders",
    noOrders: "No orders found",
    tryClearing: "Try clearing filters",
    addCustomer: "Add a new customer to get started",
    pending: "Pending",
    progress: "Progress",
    paid: "Paid",
    call: "Call",
    whatsapp: "WhatsApp",
    nextStage: "Next Stage",
    markPaid: "Mark Paid",
    home: "Home",
    customers: "Customers",
    tryOn: "Try-On",
    bills: "Bills",
    profile: "Profile",
    filterByStatus: "Filter by Status",
    filterByPayment: "Filter by Payment",
    allStatus: "All Status",
    allPayment: "All Payment",
    noMeasurements: "No Measurements Yet",
    startMeasurements: "Start by taking measurements for this customer",
    share: "Share",
    print: "Print",
    add: "Add",
    fit: "Fit",
    high: "High",
    medium: "Medium",
    low: "Low",

    // Profile Screen
    logout: "Logout",
    logoutConfirm: "Are you sure you want to logout?",
    cancel: "Cancel",
    error: "Error",
    logoutFailed: "Failed to logout",
    businessInfo: "Business Information",
    businessName: "Business Name",
    phoneNumber: "Phone Number",
    location: "Location",

    // Add Measurement Screen
    measurements: "Measurements",
    selectedGarment: "Selected Garment",
    additionalNotes: "Additional Notes",
    addNotesPlaceholder: "Add any special instructions or remarks...",
    saveMeasurements: "Save Measurements",
    saveAndContinue: "Save & Continue",
    incomplete: "Incomplete",
    fillAllFields: "Please fill all measurement fields",
    savedSuccessfully: "Measurements saved successfully",
    failedToSave: "Failed to save measurements",
    loadPrevious: "Load Previous Measurements?",
    foundSaved: "Found saved measurements for this customer",
    loadData: "Load Data",
    previousLoaded: "Previous measurements loaded",
    slim: "Slim",
    regular: "Regular",
    loose: "Loose",
    fitApplied: "fit applied",

    // Add Customer Screen
    newOrder: "New Order",
    customerDetails: "Customer Details",
    orderId: "Order ID",
    created: "Created",
    returningCustomer: "Returning Customer! 🎉",
    quickFill: "Quick Fill",
    customerName: "Customer Name",
    enterFullName: "Enter full name",
    mobileNumber: "Mobile Number",
    tenDigitMobile: "10-digit mobile",
    city: "City",
    enterCity: "Enter city",
    address: "Address",
    streetArea: "Street, area (optional)",
    deliverySchedule: "Delivery Schedule",
    tomorrow: "Tomorrow",
    threeDays: "3 Days",
    oneWeek: "1 Week",
    twoWeeks: "2 Weeks",
    pickCustomDate: "Pick custom date",
    continueToMeasurements: "Continue to Measurements",
    saving: "Saving...",
    incompleteForm: "Incomplete Form",
    fillRequired: "Please fill all required fields",
    specialInstructions: "Special instructions (optional)...",

    // Measurement Field Names
    "Chest": "Chest",
    "Stomach (Pet)": "Stomach",
    "Seat (Hip)": "Seat (Hip)",
    "Shoulder": "Shoulder",
    "Back": "Back",
    "Waist": "Waist",
    "Thigh": "Thigh",
    "Knee": "Knee",
    "Calf": "Calf",
    "Bottom": "Bottom",
    "Sleeve Length": "Sleeve Length",
    "Sleeve Round": "Sleeve Round",
    "Sleeve End": "Sleeve End",
    "Armhole": "Armhole",
    "Collar": "Collar",
    "Front Neck": "Front Neck",
    "Back Neck": "Back Neck",
    "Shirt Length": "Shirt Length",
    "Full Length": "Full Length",
    "Inside Length": "Inside Length",
    "Seat Length": "Seat Length",
    "Kurta Length": "Kurta Length",
    "Safari Length": "Safari Length",
    "Coti Length": "Coti Length",
    "Blazer Length": "Blazer Length",
    "in": "in",
  },
  gu: {
    // Home Screen
    greeting: "નમસ્તે યોગી! 👋",
    actionRequired: "કાર્યવાહી જરૂરી",
    overdue: "મુદત પૂરી",
    dueToday: "આજે મુદત",
    todaySnapshot: "આજનો સારાંશ",
    inProgress: "ચાલુ",
    ready: "તૈયાર",
    trial: "ટ્રાયલ",
    unpaid: "બાકી",
    cashIn: "રોકડ આવક",
    outstanding: "બાકી રકમ",
    profit: "નફો",
    searchPlaceholder: "નામ, ફોન, ઓર્ડરથી શોધો...",
    status: "સ્થિતિ",
    payment: "ચુકવણી",
    today: "આજે",
    upcoming: "આવનાર",
    allOrders: "બધા ઓર્ડર",
    orders: "ઓર્ડર",
    order: "ઓર્ડર",
    focusMode: "🔥 ફોકસ મોડ",
    loading: "તમારા ઓર્ડર લોડ થઈ રહ્યા છે...",
    allClear: "આજે બધું પૂર્ણ થયું! 🎉",
    noUpcoming: "આવનાર ઓર્ડર નથી",
    noOrders: "ઓર્ડર મળ્યા નથી",
    tryClearing: "ફિલ્ટર્સ સાફ કરો",
    addCustomer: "નવા ગ્રાહક ઉમેરો",
    pending: "બાકી",
    progress: "ચાલુ",
    paid: "ચુકવ્યું",
    call: "કૉલ",
    whatsapp: "વોટ્સએપ",
    nextStage: "આગળ",
    markPaid: "ચુકવ્યું",
    home: "હોમ",
    customers: "ગ્રાહકો",
    tryOn: "ટ્રાય-ઓન",
    bills: "બિલ",
    profile: "પ્રોફાઇલ",
    filterByStatus: "સ્થિતિ પ્રમાણે ફિલ્ટર",
    filterByPayment: "ચુકવણી પ્રમાણે ફિલ્ટર",
    allStatus: "બધી સ્થિતિ",
    allPayment: "બધી ચુકવણી",
    noMeasurements: "માપ લીધેલ નથી",
    startMeasurements: "આ ગ્રાહક માટે માપ લેવાનું શરૂ કરો",
    share: "શેર",
    print: "પ્રિન્ટ",
    add: "ઉમેરો",
    fit: "ફિટ",
    high: "ઊંચું",
    medium: "મધ્યમ",
    low: "નીચું",

    // Profile Screen
    logout: "લૉગઆઉટ",
    logoutConfirm: "શું તમે ખરેખર લૉગઆઉટ કરવા માંગો છો?",
    cancel: "રદ કરો",
    error: "ભૂલ",
    logoutFailed: "લૉગઆઉટ નિષ્ફળ",
    businessInfo: "વ્યવસાય માહિતી",
    businessName: "વ્યવસાયનું નામ",
    phoneNumber: "ફોન નંબર",
    location: "સ્થાન",

    // Add Measurement Screen
    measurements: "માપ",
    selectedGarment: "પસંદ કરેલ વસ્ત્ર",
    additionalNotes: "વધારાની નોંધ",
    addNotesPlaceholder: "કોઈપણ ખાસ સૂચનાઓ ઉમેરો...",
    saveMeasurements: "માપ સાચવો",
    saveAndContinue: "સાચવો અને ચાલુ રાખો",
    incomplete: "અપૂર્ણ",
    fillAllFields: "કૃપા કરીને બધા માપ ભરો",
    savedSuccessfully: "માપ સફળતાપૂર્વક સાચવ્યા",
    failedToSave: "માપ સાચવવામાં નિષ્ફળ",
    loadPrevious: "અગાઉના માપ લોડ કરો?",
    foundSaved: "આ ગ્રાહક માટે સાચવેલા માપ મળ્યા",
    loadData: "ડેટા લોડ કરો",
    previousLoaded: "અગાઉના માપ લોડ થયા",
    slim: "પાતળું",
    regular: "નિયમિત",
    loose: "ઢીલું",
    fitApplied: "ફિટ લાગુ થયું",

    // Add Customer Screen
    newOrder: "નવો ઓર્ડર",
    customerDetails: "ગ્રાહક વિગતો",
    orderId: "ઓર્ડર આઈડી",
    created: "બનાવ્યું",
    returningCustomer: "પાછા ફરતા ગ્રાહક! 🎉",
    quickFill: "ઝડપથી ભરો",
    customerName: "ગ્રાહકનું નામ",
    enterFullName: "સંપૂર્ણ નામ દાખલ કરો",
    mobileNumber: "મોબાઇલ નંબર",
    tenDigitMobile: "10 અંકનો મોબાઇલ",
    city: "શહેર",
    enterCity: "શહેર દાખલ કરો",
    address: "સરનામું",
    streetArea: "શેરી, વિસ્તાર (વૈકલ્પિક)",
    deliverySchedule: "ડિલિવરી શેડ્યૂલ",
    tomorrow: "આવતી કાલે",
    threeDays: "3 દિવસ",
    oneWeek: "1 અઠવાડિયું",
    twoWeeks: "2 અઠવાડિયા",
    pickCustomDate: "કસ્ટમ તારીખ પસંદ કરો",
    continueToMeasurements: "માપ માટે ચાલુ રાખો",
    saving: "સાચવી રહ્યા છીએ...",
    incompleteForm: "અપૂર્ણ ફોર્મ",
    fillRequired: "કૃપા કરીને બધી જરૂરી ફીલ્ડ ભરો",
    specialInstructions: "ખાસ સૂચનાઓ (વૈકલ્પિક)...",

    // Measurement Field Names (Gujarati)
    "Chest": "છાતી",
    "Stomach (Pet)": "પેટ",
    "Seat (Hip)": "હિપ",
    "Shoulder": "ખભા",
    "Back": "પીઠ",
    "Waist": "કમર",
    "Thigh": "જાંઘ",
    "Knee": "ઘૂંટણ",
    "Calf": "પીંડળી",
    "Bottom": "પગનો છેડો",
    "Sleeve Length": "બાયની લંબાઈ",
    "Sleeve Round": "બાયનો ગોળાકાર",
    "Sleeve End": "બાયનો છેડો",
    "Armhole": "બાયનો છિદ્ર",
    "Collar": "કોલર",
    "Front Neck": "સામેની ગરદન",
    "Back Neck": "પાછળની ગરદન",
    "Shirt Length": "શર્ટની લંબાઈ",
    "Full Length": "સંપૂર્ણ લંબાઈ",
    "Inside Length": "અંદરની લંબાઈ",
    "Seat Length": "સીટની લંબાઈ",
    "Kurta Length": "કુર્તાની લંબાઈ",
    "Safari Length": "સફારીની લંબાઈ",
    "Coti Length": "કોટીની લંબાઈ",
    "Blazer Length": "બ્લેઝરની લંબાઈ",
    "in": "ઇંચ",
  },
};

export const LanguageProvider = ({ children }) => {
  const [isEnglish, setIsEnglish] = useState(true);
  const [toggleAnim] = useState(new Animated.Value(0));

  const toggleLanguage = () => {
    const toValue = isEnglish ? 1 : 0;
    Animated.spring(toggleAnim, {
      toValue,
      tension: 60,
      friction: 8,
      useNativeDriver: false,
    }).start();
    setIsEnglish(!isEnglish);
  };

  const t = isEnglish ? translations.en : translations.gu;

  return (
    <LanguageContext.Provider
      value={{
        isEnglish,
        toggleLanguage,
        toggleAnim,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};